site_name: Keyword-Categories
nav:
  - Home: README.md
  - Contributing: contributing.md
theme:
  name: 'material'
repo_url: https://github.com/Shopee-SEO/Keyword-Categories
remote_branch: gh-pages
remote_name: origin
