train_csv_path = '../../dataset/level1_80/clean/valid.csv'
# valid_csv_path = '../../dataset/level1_80/clean/valid.csv'
test_csv_path = '../../dataset/level1_80/clean/test.csv'
label_name = 'level1_global_be_category_id'
project_name = 'shopee_title_image_pretrained_model'
image_dir = '../../dataset/level1_valid_test_images_resize'
