[cache]
search_history_path = "cache/.search_history"

[dataset]
val_csv_path = "data/val.csv"

[vocab]
min_freq = 200
vocab_path = "data/vocab_val.txt"
use_stop_words = true
stop_words_paths = ["stopwords/baidu_stopwords.txt", "stopwords/hit_stopwords.txt"]


[evaluate_news]
limit = 3
test_data_path = "data/evaluate/性能测试原材料.json"
evaluate_result_path = "性能测试结果/news/milvus.bow.v2.json"

[evaluate_title]
limit = 10
test_data_path = "data/evaluate/标题测试原材料.csv"
evaluate_result_path = "性能测试结果/title/milvus.bow.v3_1.csv"

[milvus]
version = "milvus.bow.v3_2"
metric_type = "COSINE"
embedding_name = "content_embedding"

[milvus.bow.v1]
db_name = "database/milvus_bow_v1.db"
collection_name = "bow_title_content_collection_v1"
description = "content embedding use bow without stop words"

[milvus.bow.v2]
db_name = "database/milvus_bow_v2.db"
collection_name = "bow_title_content_collection_v2"
description = "content embedding use bow with stop words"

[milvus.bow.v2_1000]
db_name = "database/milvus_bow_v2_1000.db"
collection_name = "bow_title_content_collection_v2_1000"
description = "content embedding use bow with stop words and dataset size=1000"


[milvus.bow.v3]
db_name = "database/milvus_bow_v3.db"
collection_name = "bow_title_content_collection_v3"
description = "content embedding use bow with stop words ,vocab_val.txt, min_freq=1000"

[milvus.bow.v3_1]
db_name = "database/milvus_bow_v3_1.db"
collection_name = "bow_title_content_collection_v3_1"
description = "content embedding use bow with stop words ,vocab_val.txt, min_freq=350"

[milvus.bow.v3_2]
db_name = "database/milvus_bow_v3_2.db"
collection_name = "bow_title_content_collection_v3_2"
description = "content embedding use bow with stop words ,vocab_val.txt, min_freq=200"
