[cache]
search_history_path = "cache/.search_history"

[dataset]
val_csv_path = "data/val.csv"

[vocab]
min_freq = 1000
vocab_path = "data/vocab.txt"
use_stop_words = true
stop_words_path = "stopwords/baidu_stopwords.txt"


[evaluate]
test_data_path = "性能测试原材料.json"
evaluate_result_path = "性能测试/milvus.bow.v1.json"

[milvus]
version = "milvus.bow.v1"
metric_type = "COSINE"
embedding_name = "content_embedding"

[milvus.bow.v1]
db_name = "database/milvus_bow_v1.db"
collection_name = "bow_title_content_collection_v1"
description = "content embedding use bow without stop words"

[milvus.bow.v2]
db_name = "database/milvus_bow_v2.db"
collection_name = "bow_title_content_collection_v2"
description = "content embedding use bow with stop words"
