[cache]
search_history_path = "cache/.search_history"

[dataset]
val_csv_path = "data/val.csv"


[milvus]
version = "milvus.bow.v4_2"
metric_type = "COSINE"
embedding_name = "content_embedding"

[milvus.bow.v3_2]
db_name = "database/milvus_bow_v3_2.db"
collection_name = "bow_title_content_collection_v3_2"
description = "content embedding use bow with stop words ,vocab_val.txt, min_freq=200"

[milvus.bow.v4]
db_name = "database/milvus_bow_v4.db"
collection_name = "bow_title_content_collection_v4"
description = "content embedding use bow(tf-idf) with stop words ,vocab_val.txt, min_freq=200"

[milvus.bow.v4_1]
db_name = "database/milvus_bow_v4_1.db"
collection_name = "bow_title_content_collection_v4_1"
description = "content embedding use bow(tf-idf) with stop words ,vocab_val.txt, min_freq=200, max_freq=105190"

[milvus.bow.v4_2]
db_name = "database/milvus_bow_v4_2.db"
collection_name = "bow_title_content_collection_v4_2"
description = "content embedding use bow(tf-idf) with stop words ,vocab_val.txt, min_freq=200, max_freq=80501"

[evaluate_news]
limit = 3
test_data_path = "data/evaluate/性能测试原材料.json"
evaluate_result_path = "性能测试结果/news/milvus.bow.v2.json"

[vocab]
min_freq = 200
max_freq = 80501
vocab_path = "data/vocab_val.txt"
word_counts_path = "data/idf/word_counts.json"
word_idf_path = "data/idf/word_idf.json"
use_stop_words = true
stop_words_paths = ["stopwords/baidu_stopwords.txt", "stopwords/hit_stopwords.txt"]


[evaluate_title]
limit = 10
test_data_path = "data/evaluate/标题测试原材料.csv"
evaluate_result_path = "性能测试结果/title/milvus.bow.v4_2.csv"