version = "milvus.bow.v7_8"
project = "text-similarity-word2vec-siamese"

[cache]
search_history_path = "cache/.search_history"
best_model_path = 'checkpoint1/350_15000000_200_256_512_0.0001_0.0001_15_1.0_best.pth'
pre_trained_model_path = 'pre-trained/350_15000000_5_10_0.003_0.0001_200_512_4_best.pth'

[dataset]
train_csv_path = "data/val_10000.csv"
val_csv_path = "data/test_1000.csv"
test_csv_path = "data/val_10000.csv" # 提取测试集的特征，存储到 milvus 中


[milvus]
metric_type = "COSINE"
embedding_name = "content_embedding"

[milvus.bow.v7]
db_name = "database/milvus_bow_v7.db"
collection_name = "bow_title_content_collection_v7"
description = "content embedding use CBOW-Siamese, 词向量取平均, 不使用预训练 embedding"

[milvus.bow.v7_1]
db_name = "database/milvus_bow_v7_1.db"
collection_name = "bow_title_content_collection_v7_1"
description = "content embedding use CBOW-Siamese, 词向量取平均, 使用预训练 embedding"

[milvus.bow.v7_2]
db_name = "database/milvus_bow_v7_2.db"
collection_name = "bow_title_content_collection_v7_2"
description = "content embedding use CBOW-Siamese, 词向量取平均, 使用预训练 embedding, 提取 val.csv 的特征"

[milvus.bow.v7_3]
db_name = "database/milvus_bow_v7_3.db"
collection_name = "bow_title_content_collection_v7_3"
description = "content embedding use CBOW-Siamese, 词向量取平均, 不使用预训练 embedding, 提取 val.csv 的特征"

[milvus.bow.v7_4]
db_name = "database/milvus_bow_v7_4.db"
collection_name = "bow_title_content_collection_v7_4"
description = "content embedding use CBOW-Siamese, 词向量取平均, 不使用预训练 embedding, 提取 val_10000.csv 的特征, temperature = 0.1"

[milvus.bow.v7_5]
db_name = "database/milvus_bow_v7_5.db"
collection_name = "bow_title_content_collection_v7_5"
description = "content embedding use CBOW-Siamese, 词向量取平均, 不使用预训练 embedding, 提取 val_10000.csv 的特征, temperature = 1"

[milvus.bow.v7_6]
db_name = "database/milvus_bow_v7_6.db"
collection_name = "bow_title_content_collection_v7_6"
description = "content embedding use CBOW-Siamese, 词向量最大池化, 不使用预训练 embedding, 提取 val_10000.csv 的特征, temperature = 1"

[milvus.bow.v7_7]
db_name = "database/milvus_bow_v7_7.db"
collection_name = "bow_title_content_collection_v7_7"
description = "content embedding use CBOW-Siamese, 使用 idf 加权, 不使用预训练 embedding, 提取 val_10000.csv 的特征, temperature = 1"

[milvus.bow.v7_8]
db_name = "database/milvus_bow_v7_8.db"
collection_name = "bow_title_content_collection_v7_8"
description = "content embedding use CBOW-Siamese, 使用 idf 加权, 使用预训练 embedding, 提取 val_10000.csv 的特征, temperature = 1"

[vocab]
use_pretrained_model = false
min_freq = 350
max_freq = 15000000
vocab_path = "data/vocab_val.txt"
use_stop_words = true
embedding_dim = 200
projection_dim = 256
batch_size = 512
learning_rate = 1e-4
weight_decay = 1e-4
epochs = 15
temperature = 1
max_title_length = 16
max_content_length = 512
idf_path = "data/idf/word_idf.json"
stop_words_paths = ["stopwords/baidu_stopwords.txt", "stopwords/hit_stopwords.txt"]


[evaluate_title]
limit = 10
test_data_path = "data/evaluate/标题测试原材料_1000_from_val_10000.csv"
evaluate_result_path = "性能测试结果/title/milvus.bow.v7_8.csv"