[cache]
search_history_path = "cache/.search_history"
val_cbow_dataset_cache_path = "cache/val_cbow_2.pkl"
val_cbow_model_cache_path = "cache/batch_size32-epochs10-lr1e-05-wd1e-05-projectionTrue_best_val_loss_epoch.pth"
val_cbow_model_checkpoint_path = "checkpoint/val_cbow_2.pth"

[dataset]
train_csv_path = "data/val_10000.csv"
val_csv_path = "data/test_1000.csv"

[milvus]
version = "milvus.bert.v9_5"
metric_type = "COSINE"
embedding_name = "content_embedding"

[milvus.bert.v9]
db_name = "database/milvus_bert_v9.db"
collection_name = "bert_title_content_collection_v9"
description = "content embedding use bert"

[milvus.bert.v9_1]
db_name = "database/milvus_bert_v9_1.db"
collection_name = "bert_title_content_collection_v9_1"
description = "content embedding use bert + siamese 孪生网络"

[milvus.bert.v9_2]
db_name = "database/milvus_bert_v9_2.db"
collection_name = "bert_title_content_collection_v9_2" # 基于 val.csv 生产 database
description = "content embedding use bert + siamese 孪生网络 + 对称loss + 大训练集"

[milvus.bert.v9_3]
db_name = "database/milvus_bert_v9_3.db"
collection_name = "bert_title_content_collection_v9_3"
description = "content embedding use bert + siamese 孪生网络 + 对称loss + val_10000.csv 训练集"

[milvus.bert.v9_3_1]
db_name = "database/milvus_bert_v9_3_1.db" # 基于 test_10000.csv 生产 database
collection_name = "bert_title_content_collection_v9_3_1"
description = "content embedding use bert + siamese 孪生网络 + 对称loss + val_10000.csv 训练集"

[milvus.bert.v9_4]
db_name = "database/milvus_bert_v9_4.db"
collection_name = "bert_title_content_collection_v9_4"
description = "content embedding use hfl/chinese-bert-wwm + siamese 孪生网络 + 对称loss + val_10000.csv 训练集"

[milvus.bert.v9_5]
db_name = "database/milvus_bert_v9_5.db"
collection_name = "bert_title_content_collection_v9_5"
description = "content embedding use bert-clip + siamese 孪生网络 + 对称loss + val_10000.csv 训练集"

[vocab]
max_length = 512
embedding_dim = 768
projection_dim = 256
bert_name = "bert-base-chinese"
vocab_path = "data/vocab_val.txt"


[evaluate_title]
limit = 10
test_data_path = "data/evaluate/标题测试原材料_1000_from_val_10000.csv"
evaluate_result_path = "性能测试结果/title/milvus.bert.v9_5.csv"
