[cache]
search_history_path = "cache/.search_history"
val_cbow_dataset_cache_path = "cache/val_cbow_2.pkl"
val_cbow_model_cache_path = "cache/val_cbow_2_model.pth"
val_cbow_model_checkpoint_path = "checkpoint/val_cbow_2.pth"

[dataset]
val_csv_path = "data/val.csv"


[milvus]
version = "milvus.bert.v9"
metric_type = "COSINE"
embedding_name = "content_embedding"

[milvus.bert.v9]
db_name = "database/milvus_bert_v9.db"
collection_name = "bert_title_content_collection_v9"
description = "content embedding use bert"

[vocab]
max_length = 512
embedding_dim = 768
bert_name = "bert-base-chinese"
vocab_path = "data/vocab_val.txt"


[evaluate_title]
limit = 10
test_data_path = "data/evaluate/标题测试原材料.csv"
evaluate_result_path = "性能测试结果/title/milvus.bert.v9.csv"