[cache]
search_history_path = "cache/.search_history"
val_cbow_dataset_cache_path = "cache/val_cbow_2.pkl"
val_cbow_model_cache_path = "cache/val_cbow_2_model.pth"
val_cbow_model_checkpoint_path = "checkpoint/val_cbow_2.pth"

[dataset]
val_csv_path = "data/val.csv"


[milvus]
version = "milvus.bert.v9"
metric_type = "COSINE"
embedding_name = "content_embedding"

[milvus.bow.v5]
db_name = "database/milvus_bow_v5.db"
collection_name = "bow_title_content_collection_v5"
description = "content embedding use CBOW, epoch=4, window_size=2, min_freq=200"

[milvus.bert.v9]
db_name = "database/milvus_bert_v9.db"
collection_name = "bert_title_content_collection_v9"
description = "content embedding use bert"

[vocab]
window_size = 2
min_freq = 200
vocab_path = "data/vocab_val.txt"
use_stop_words = true
embedding_dim = 768
stop_words_paths = ["stopwords/baidu_stopwords.txt", "stopwords/hit_stopwords.txt"]


[evaluate_title]
limit = 10
test_data_path = "data/evaluate/标题测试原材料.csv"
evaluate_result_path = "性能测试结果/title/milvus.bow.v5.csv"