[cache]
search_history_path = "cache/.search_history"
val_cbow_dataset_cache_path = "cache/val_cbow_2.pkl"
val_cbow_model_cache_path = "cache/batch_size32-epochs5-lr3e-05-wd0.0001-projectionTrue_final.pth"
val_cbow_model_checkpoint_path = "checkpoint/val_cbow_2.pth"

[dataset]
train_csv_path = "data/val.csv"
val_csv_path = "data/val.csv"

[milvus]
version = "milvus.bert.v9_2"
metric_type = "COSINE"
embedding_name = "content_embedding"

[milvus.bert.v9]
db_name = "database/milvus_bert_v9.db"
collection_name = "bert_title_content_collection_v9"
description = "content embedding use bert"

[milvus.bert.v9_1]
db_name = "database/milvus_bert_v9_1.db"
collection_name = "bert_title_content_collection_v9_1"
description = "content embedding use bert + siamese 孪生网络"

[milvus.bert.v9_2]
db_name = "database/milvus_bert_v9_2.db"
collection_name = "bert_title_content_collection_v9_2" # 基于 val.csv 生产 database
description = "content embedding use bert + siamese 孪生网络 + 对称loss + 大训练集"

[vocab]
max_length = 512
embedding_dim = 768
use_projection = true
bert_name = "bert-base-chinese"
vocab_path = "data/vocab_val.txt"


[evaluate_title]
limit = 10
test_data_path = "data/evaluate/标题测试原材料.csv"
evaluate_result_path = "性能测试结果/title/milvus.bert.v9_1.csv"
