version = "milvus.bow.v5_3"

[cache]
search_history_path = "cache/.search_history"
val_cbow_dataset_cache_path = "cache/val_cbow_5_350.pkl"
val_cbow_model_cache_path = "checkpoint/val_cbow_5_350_final.pth"
val_cbow_model_checkpoint_path = "checkpoint/val_cbow_5_350.pth"

[dataset]
val_csv_path = "data/val.csv"
test_csv_path = "data/test_1000.csv"


[milvus]
metric_type = "COSINE"
embedding_name = "content_embedding"

[milvus.bow.v5]
db_name = "database/milvus_bow_v5.db"
collection_name = "bow_title_content_collection_v5"
description = "content embedding use CBOW, epoch=4, window_size=2, min_freq=200"

[milvus.bow.v5_1]
db_name = "database/milvus_bow_v5_1.db"
collection_name = "bow_title_content_collection_v5_1"
description = "content embedding use CBOW, epoch=10, window_size=2, min_freq=200"

[milvus.bow.v5_2]
db_name = "database/milvus_bow_v5_2.db"
collection_name = "bow_title_content_collection_v5_2"
description = "content embedding use CBOW, epoch=15, window_size=5, min_freq=200"

[milvus.bow.v5_3]
db_name = "database/milvus_bow_v5_3.db"
collection_name = "bow_title_content_collection_v5_3"
description = "content embedding use CBOW, epoch=15, window_size=5, min_freq=350"

[vocab]
window_size = 5
min_freq = 350
max_freq = 80501
vocab_path = "data/vocab_val.txt"
use_stop_words = true
embedding_dim = 200
stop_words_paths = ["stopwords/baidu_stopwords.txt", "stopwords/hit_stopwords.txt"]


[evaluate_title]
limit = 10
test_data_path = "data/evaluate/标题测试原材料.csv"
evaluate_result_path = "性能测试结果/title/milvus.bow.v5_3.csv"