version = "milvus.gensim.v6"

[cache]
search_history_path = "cache/.search_history"
val_cbow_dataset_cache_path = "cache/val_cbow_5_350.pkl"
test_cbow_dataset_cache_path = "cache/test_1000_cbow.pkl"
val_cbow_model_cache_path = "checkpoint/10_5_5_100_final.pth"
val_cbow_model_checkpoint_path = "checkpoint/val_cbow_5_350.pth"

[dataset]
train_csv_dataset = "data/val.csv"
val_csv_path = "data/test_1000.csv"


[milvus]
metric_type = "COSINE"
embedding_name = "content_embedding"

[milvus.gensim.v6]
db_name = "database/milvus_gensim_v6.db"
collection_name = "gensim_title_content_collection_v6"
description = "content embedding use gensim word2vector"

[vocab]
window = 8
min_freq = 500
max_freq = 105190
vocab_path = "data/vocab.txt"
use_stop_words = true
embedding_dim = 200
stop_words_paths = ["stopwords/baidu_stopwords.txt", "stopwords/hit_stopwords.txt"]


[evaluate_title]
limit = 10
test_data_path = "data/evaluate/标题测试原材料.csv"
evaluate_result_path = "性能测试结果/title/milvus.gensim.v6.csv"